# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def shared_pods
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
end

use_frameworks!

target 'IntegrationKit' do
  shared_pods

  target 'IntegrationKitTests' do
    pod 'RxBlocking', '6.5.0'
    pod 'RxTest', '6.5.0'
  end
end

target 'IntegrationWatchOS' do
  shared_pods

  target 'IntegrationWatchOSTests' do
  end
end

